<a href="https://colab.research.google.com/github/masoodkhanpatel/kernel-distance-cosinesimilarity/blob/main/kernel_distance_cosinesimilarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X1 = np.array([[0.8, -0.2, 0.2, -1.3, 0.2, 1.0, 1.2, 0.1, -2.3, 0.3],
      [2.4, 0.2, 1.8, 0.4, 2.7, 2.8, 2.8, 0.0, 0.3, 0.7],
      [-0.5, -1.3, -1.2, -1.3, -0.3, -0.9, -0.1, -1.1, -2.9, -.7]])

In [ ]:
X2 = np.array([[3.0, 0.4, 1.9, 1.3, 2.7, 3.5, 2.4, 1.6, 1.0, 1.0],
      [-1.4, 0.3, -0.1, -1.3, 1.5, -1.8, -0.6, 0.5, -0.6, -0.6],
      [2.5, 2.0, 1.7, 1.8, 3.0, 3.2, 2.3, 1.4, 1.7, 2.2]])

In [ ]:
print("Exercise 1:")

Exercise 1:


In [ ]:
X = np.concatenate((X1,X2), axis = 1)
print("\nCombined Dataset X:\n", X)


Combined Dataset X:
 [[ 0.8 -0.2  0.2 -1.3  0.2  1.   1.2  0.1 -2.3  0.3  3.   0.4  1.9  1.3
   2.7  3.5  2.4  1.6  1.   1. ]
 [ 2.4  0.2  1.8  0.4  2.7  2.8  2.8  0.   0.3  0.7 -1.4  0.3 -0.1 -1.3
   1.5 -1.8 -0.6  0.5 -0.6 -0.6]
 [-0.5 -1.3 -1.2 -1.3 -0.3 -0.9 -0.1 -1.1 -2.9 -0.7  2.5  2.   1.7  1.8
   3.   3.2  2.3  1.4  1.7  2.2]]


In [ ]:
print("\nMean vector of X:", np.mean(X, axis=1))


Mean vector of X: [0.94  0.5   0.575]


In [ ]:
variance_X = np.var(X, ddof=0, axis=1 )
print("\nVariance of X:", variance_X)
print("Total Variance:", sum(variance_X))


Variance of X: [1.8464   1.916    3.003875]
Total Variance: 6.766274999999999


In [ ]:
cov_mat = np.cov(X, ddof=0)
print("\nCovariance Matrix of X:\n", cov_mat)


Covariance Matrix of X:
 [[ 1.8464   -0.5755    2.03    ]
 [-0.5755    1.916    -1.2275  ]
 [ 2.03     -1.2275    3.003875]]


In [ ]:
evalue, evect = np.linalg.eig(cov_mat)

In [ ]:
print("\nEigenvalues:\n", evalue)


Eigenvalues:
 [5.09276211 0.25165885 1.42185405]


In [ ]:
print("\nEigenvectors:\n", evect)


Eigenvectors:
 [[-0.53723389  0.7366165   0.41082342]
 [ 0.38691292 -0.21757334  0.89608048]
 [-0.7494519  -0.64035769  0.16811867]]


In [ ]:
pca_sorted_index = np.argsort(-1*evalue)
print("\nFirst PCA:\n", evect[:, pca_sorted_index[0]])
print("\nSecond PCA:\n", evect[:, pca_sorted_index[1]])


First PCA:
 [-0.53723389  0.38691292 -0.7494519 ]

Second PCA:
 [0.41082342 0.89608048 0.16811867]


In [ ]:
print("\n-----------------------------------------------------------------------")


-----------------------------------------------------------------------


In [ ]:
print("Exercise 2:")

Exercise 2:


In [ ]:
matrix = [[5, 3, 1, 0, 3, 0, 2],
       [0, 0, 2, 3, 7, 4, 0],
       [0, 0, 0, 4, 0, 3, 1],
       [3, 2, 2, 0, 0, 0, 3]] 

In [ ]:
similarity_matrix = []
for a in matrix:
  row = []
  for b in matrix:
    similarity = np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b))
    row.append(similarity)
  similarity_matrix.append(row)
similarity_matrix = np.array(similarity_matrix)
print("\nSimilarity Matrix:\n", similarity_matrix)


Similarity Matrix:
 [[1.         0.37588926 0.05661385 0.82090085]
 [0.37588926 1.         0.53293871 0.08882312]
 [0.05661385 0.53293871 1.         0.11538462]
 [0.82090085 0.08882312 0.11538462 1.        ]]


In [ ]:
print("\n-----------------------------------------------------------------------")


-----------------------------------------------------------------------


In [ ]:
print("Exercise 3:")

Exercise 3:


In [ ]:
x = np.array([1, -2, 1])
y = np.array([0, -1, 2])
z = np.array([-2, 0, 1])

In [ ]:
def K(a, b):
  return (1 + np.dot(a, b))**2

In [ ]:
print("\nK(x, y): ", K(x, y))
print("K(x, z): ", K(x, z))
print("K(y, z): ", K(y, z))


K(x, y):  25
K(x, z):  0
K(y, z):  9


In [ ]:
def kernel_matrix(x):
  k = []
  for i in x:
    row = []
    for j in x:
      row.append(K(i,j))
    k.append(row)
  k = np.array(k)
  return k

In [ ]:
vectors = [x, y, z]

In [ ]:
print("\nKernel Matrix for x, y and z:\n", kernel_matrix(vectors))


Kernel Matrix for x, y and z:
 [[49 25  0]
 [25 36  9]
 [ 0  9 36]]


In [ ]:
def dist_in_feature_space(a, b):
  temp = K(a, a) + K(b, b) - 2*K(a, b)
  return np.sqrt(temp)

In [ ]:
distance_matrix = []
for a in vectors:
  row = []
  for b in vectors:
    distance = dist_in_feature_space(a, b)
    row.append(distance)
  distance_matrix.append(row)
distance_matrix = np.array(distance_matrix)
print("\nDistance Matrix:\n", distance_matrix)


Distance Matrix:
 [[0.         5.91607978 9.21954446]
 [5.91607978 0.         7.34846923]
 [9.21954446 7.34846923 0.        ]]


In [ ]:
def cosine_similarity(a, b):
  return K(a, b)/np.sqrt(K(a, a)*K(b, b))

In [ ]:
print("\nCosine Similarity(x, y): ", cosine_similarity(x, y))
print("Cosine Similarity(x, z): ", cosine_similarity(x, z))
print("Cosine Similarity(y, z): ", cosine_similarity(y, z))


Cosine Similarity(x, y):  0.5952380952380952
Cosine Similarity(x, z):  0.0
Cosine Similarity(y, z):  0.25


In [ ]:
cosine_similarity_matrix = []
for a in vectors:
  row = []
  for b in vectors:
    cosine_sim = cosine_similarity(a, b)
    row.append(cosine_sim)
  cosine_similarity_matrix.append(row)
cosine_similarity_matrix = np.array(cosine_similarity_matrix)
print("\nCosine Similarity Matrix:\n", cosine_similarity_matrix)


Cosine Similarity Matrix:
 [[1.        0.5952381 0.       ]
 [0.5952381 1.        0.25     ]
 [0.        0.25      1.       ]]
